@startuml
class CarManager{
    + getFromDb(final String carId): Car
    + getCarsNames(): String
    + getBestCar(): Car
}

class Car{
-  _id: String
- model: String
- _brand: String
+ getId()
+ getModel()
+ getBrand()
}

CarManager o-- Car

@enduml