@startuml
'https://plantuml.com/class-diagram





Door <|.. SensingDoor
Door <|.. TimedDoor
Sensor ..> Door
Timer ..> Door

interface Door {
lock()
unlock()
open()
close()
proximityCallback()
timeOutCallback()
}

class SensingDoor {
-_locked : boolean
-_opened : boolean
lock()
unlock()
open()
close()
proximityCallback()
timeOutCallback()
}

class TimedDoor {
-_locked : boolean
-_opened : boolean
lock()
unlock()
open()
close()
proximityCallback(
timeOutCallback()
}

class Sensor {
+register()
-isPersonClose():boolean
}

class Timer {
+register()
}



@enduml